@startuml SequenceDiagram
actor User1 
participant UserInterface1
participant Controller1
database jsonFile1

User1 -> UserInterface1: Inputs data for a new workout
UserInterface1-> Controller1: data is stored in a workout
Controller1 -> jsonFile1: workout added to file

actor User2
participant UserInterface2
participant Controller2
participant Core
database jsonFile2

User2 -> UserInterface2: User request viewing previous workouts
UserInterface2 -> Controller2: loadExerciseHistory()
Controller2 -> Core: getMostRecentWorkouts()
Core -> jsonFile2: request users workout history
jsonFile2 -> Core: Respond with users history
Core -> Controller2: Respond with list of workouts
Controller2 -> UserInterface2: adds workouts to listView
UserInterface2 -> User2: displays history
@enduml
